### ISSUE TITLE
微信版本只能和你提供的一样吗？

### ISSUE THREAD

**Issue by onedayday-wb** [CJ-from-LosSantos/network-tools#10]
微信版本只能和你提供的一样吗？

**Comment by NC-Cj** [comment]
yes

**Comment by onedayday-wb** [comment]
那参数中的listenRoomList（监听的房间号）这个去哪儿找啊

**Comment by NC-Cj** [comment]
你需要开启debug模式，查找仔细观察接口返回出来的xml信息，找到带roomchat的号码

**Comment by onedayday-wb** [comment]
> 你需要开启debug模式，查找仔细观察接口返回出来的xml信息，找到带roomchat的号码

好的，我再试试

**Comment by onedayday-wb** [comment]
> 你需要开启debug模式，查找仔细观察接口返回出来的xml信息，找到带roomchat的号码

你好，我找到了带有`roomchat`的`room_wxid`，放在了`.yml`里面，

```
listenRoomList:
- 21735243552@chatroom
- 21431405764@chatroom
listenWeChatIdList:
root: ./wx/robot.py
script:
  fileName: ./script/spider.py
  bySet: BySpiderCommand
mysqlConnStr:
name: test_robot
debug: true
template: listen group
```
然后`Carl start`的时候，就失败了，我发现我监听`template: listen individual`的时候就可以，一旦监听群组消息`template: listen group`就不行了，这是咋回事啊？

**Comment by NC-Cj** [comment]
你需要使用另一个模板，带有&符号的
