### ISSUE TITLE
bot 发送图片时只发送图片路径

### ISSUE THREAD

**Issue by HaibaraZ3R0** [CJ-from-LosSantos/network-tools#6]

**Comment by HaibaraZ3R0** [comment]
在调用
`def get_test(self,key):
        filename = r'C:\Users\a\Desktop\bot-console-master\bot-console-master\dist\images\123.png'
        return filename`
之后 bot 将图片路径作为字符串发送

**Comment by NC-Cj** [comment]
已修复，详见提交号：58b631af
