### ISSUE TITLE
启动 error

### ISSUE THREAD

**Issue by qiuyueovo** [CJ-from-LosSantos/network-tools#9]
\dist>Carl init --debug test_robot
ERROR: The function received no value for the required argument: name
Usage: Carl init NAME <flags>
  optional flags:        --debug | --template

For detailed information on this command, run:
  Carl init --help

**Comment by NC-Cj** [comment]
文档目前还停留在上个版本，所以你现在可以先参考Carl的初始化和启动的示例，在终端输入：Carl init --help
